Use long command line options

diff --git a/opensc.SlackBuild b/opensc.SlackBuild
--- a/opensc.SlackBuild
+++ b/opensc.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # Slackware build script for OpenSC
-# Copyright (C) 2010-2020 Georgi D. Sotirov <gdsotirov@gmail.com>
+# Copyright (C) 2010-2022 Georgi D. Sotirov <gdsotirov@gmail.com>
 #
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
@@ -31,12 +31,12 @@ TMP=${TMP:-/tmp}
 CWD=${CWD:-`pwd`}
 
 if [ ! -e $TMP ]; then
-  mkdir -p $TMP # location to build the source
+  mkdir --parents $TMP # location to build the source
 fi
 
 SRC=$TMP/${NAME}-${VERSION}
 if [ -e $SRC -a -d $SRC ]; then
-  echo "Source directory '$SRC' already exists! Plaese, move it or remove it."
+  echo "Source directory '$SRC' already exists! Please, move it or remove it."
   exit 1
 fi
 
@@ -45,19 +45,19 @@ if [ -e $PKG -a -d $PKG ]; then
   echo "Package creation directory '$PKG' already exists! Please, move it or remove it."
   exit 2
 fi
-mkdir -p $PKG
+mkdir --parents $PKG
 
 # Extract the sources
 cd $TMP
-tar -xvf $CWD/${NAME}-${VERSION}.tar.?z* || exit 3
+tar --extract --verbose --file=$CWD/${NAME}-${VERSION}.tar.gz || exit 3
 cd $SRC
 fix_source
 
 # Configure
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
-./configure --build=${ARCH}-slackware-linux \
-            --host=${ARCH}-slackware-linux \
+./configure --build="${ARCH}-slackware-linux" \
+            --host="${ARCH}-slackware-linux" \
             --prefix=/usr \
             --sysconfdir=/etc \
             --localstatedir=/var \
@@ -74,7 +74,7 @@ CXXFLAGS="$SLKCFLAGS" \
             --with-xsl-stylesheetsdir=/usr/share/xml/docbook/xsl-stylesheets-1.78.1 || exit 4
 
 # Build & install
-make V=1 -j4 || exit 5
+make V=1 --jobs || exit 5
 make V=1 DESTDIR=$PKG install || exit 6
 
 # Prepare
@@ -84,25 +84,26 @@ sbin_perms $PKG
 gzip_man $PKG
 create_docs $PKG ${NAME}-${VERSION}
 
-mkdir -p $PKG/install
-install -m 644 $CWD/slack-desc     $PKG/install/slack-desc
-install -m 644 $CWD/slack-required $PKG/install/slack-required
+install --mode 755 --directory $PKG/install
+install --mode 644 $CWD/slack-desc     $PKG/install/slack-desc
+install --mode 644 $CWD/slack-required $PKG/install/slack-required
 
 SBDIR=$PKG/usr/src/slackbuilds/${NAME}-${VERSION}
-mkdir -p $SBDIR
-install -m 644 $CWD/slack-desc         $SBDIR/slack-desc
-install -m 644 $CWD/slack-required     $SBDIR/slack-required
-install -m 644 $CWD/${NAME}.SlackBuild $SBDIR/${NAME}.SlackBuild
+install --mode 755 --directory $SBDIR
+install --mode 644 $CWD/slack-desc         $SBDIR/slack-desc
+install --mode 644 $CWD/slack-required     $SBDIR/slack-required
+install --mode 644 $CWD/${NAME}.SlackBuild $SBDIR/${NAME}.SlackBuild
 
+# Create package
 cd $PKG
 PKGNAME=${NAME}-${VERSION}-${ARCH}-${BUILD}${MYIN}
-makepkg -l y -c n $PKG_DIR/${PKGNAME}.txz
-cd $PKG_DIR
-md5sum ${PKGNAME}.txz > ${PKGNAME}.txz.md5
-cat $PKG/install/slack-desc > $PKG_DIR/${PKGNAME}.txt
+makepkg --chown n --linkadd y --prepend $PKG_DIR/${PKGNAME}.txz
+md5sum $PKG_DIR/${PKGNAME}.txz > $PKG_DIR/${PKGNAME}.txz.md5
+install --mode 644 $PKG/install/slack-desc $PKG_DIR/${PKGNAME}.txt
 
+# Clean Up
 if [ "$1" == "--cleanup" ]; then
-  rm -r $SRC
-  rm -r $PKG
+  rm --recursive $SRC
+  rm --recursive $PKG
 fi
 
